/* Generated By:JJTree: Do not edit this line. ASTassignmentStatement.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package main.jjtree;

public
class ASTassignmentStatement extends SimpleNode {
  public String variableName;
  public String expressionType;
  public ASTassignmentStatement(int id) {
    super(id);
  }

  public ASTassignmentStatement(MyGrammar p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MyGrammarVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=28fbe64f18c602e18a66b9a8f9c9a2a6 (do not edit this line) */
