/* Generated By:JJTree: Do not edit this line. ASTarthExpPrime.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package main.jjtree;

public
class ASTarthExpPrime extends SimpleNode {
  public ASTarthExpPrime(int id) {
    super(id);
  }

  public ASTarthExpPrime(MyGrammar p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MyGrammarVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=ed021bfae1385597b2d4abb593eb65af (do not edit this line) */
