/* Generated By:JJTree: Do not edit this line. ASTAndExpression.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package main.jjtree;

public
class ASTAndExpression extends ASTExpression {
  public ASTAndExpression(int id) {
    super(id);
  }

  public ASTAndExpression(MyGrammar p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MyGrammarVisitor visitor, Object data) {
    return execute(visitor, data);

  }
}
/* JavaCC - OriginalChecksum=83f90d26bf84eb006de5a8d9307cdfef (do not edit this line) */
