/* Generated By:JJTree: Do not edit this line. ASTarthTermPrime.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package main.jjtree;

public
class ASTarthTermPrime extends SimpleNode {
  public ASTarthTermPrime(int id) {
    super(id);
  }

  public ASTarthTermPrime(MyGrammar p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MyGrammarVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=2d9c6c2250bcdb1d6c0785215c98be77 (do not edit this line) */
