/* Generated By:JJTree: Do not edit this line. ASTarthExp.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package main.jjtree;

public
class ASTarthExp extends SimpleNode {
  public ASTarthExp(int id) {
    super(id);
  }

  public ASTarthExp(MyGrammar p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MyGrammarVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }


}
/* JavaCC - OriginalChecksum=3346693cebd41f771422af62baecd3ae (do not edit this line) */
