/* Generated By:JJTree: Do not edit this line. ASTactualParameterList.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package main.jjtree;

public
class ASTactualParameterList extends SimpleNode {
  public ASTactualParameterList(int id) {
    super(id);
  }

  public ASTactualParameterList(MyGrammar p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MyGrammarVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=f5afcc54b49e3bf8f7bf0ff4c4069eee (do not edit this line) */
