/* Generated By:JJTree: Do not edit this line. ASTboolExpPrime.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package main.jjtree;

public
class ASTboolExpPrime extends SimpleNode {
  public ASTboolExpPrime(int id) {
    super(id);
  }

  public ASTboolExpPrime(MyGrammar p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MyGrammarVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=34f146c084ee1bf9a0dc5f3092d3e513 (do not edit this line) */
