/* Generated By:JJTree: Do not edit this line. ASTbreak2.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package main.jjtree;

public
class ASTbreak2 extends SimpleNode {
  public ASTbreak2(int id) {
    super(id);
  }

  public ASTbreak2(MyGrammar p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MyGrammarVisitor visitor, Object data) {

    return "break";
  }
}
/* JavaCC - OriginalChecksum=e21c2620ff6f80c6d5f3f2fa06b75d9e (do not edit this line) */
