/* Generated By:JJTree: Do not edit this line. ASTboolTermPrime.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package main.jjtree;

public
class ASTboolTermPrime extends SimpleNode {
  public ASTboolTermPrime(int id) {
    super(id);
  }

  public ASTboolTermPrime(MyGrammar p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MyGrammarVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=e2feb06e45d46fee2fd4fa7afe1fe22b (do not edit this line) */
