/* Generated By:JJTree: Do not edit this line. ASTbuiltInCalls.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package main.jjtree;

public
class ASTbuiltInCalls extends SimpleNode {

  public int getReturnType() {
    return -1;
  }
  public ASTbuiltInCalls(int id) {
    super(id);
  }

  public ASTbuiltInCalls(MyGrammar p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MyGrammarVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=e35dfb7afbfa23eda816062f390113ac (do not edit this line) */
