/* Generated By:JJTree: Do not edit this line. ASTfunctionBody.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package main.jjtree;

public
class ASTfunctionBody extends SimpleNode {
  public ASTfunctionBody(int id) {
    super(id);
  }

  public ASTfunctionBody(MyGrammar p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MyGrammarVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=2df22e0b720d2a785fd3ca8dd1dd92b3 (do not edit this line) */
