/* Generated By:JJTree: Do not edit this line. ASTformalParameterSection.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package main.jjtree;

import main.SemanticHelper;

public
class ASTformalParameterSection extends SimpleNode {
  public String paramName;
  public int paramType;

  public void setParamType(String paramName)
  {
   this.paramType =   SemanticHelper.getIntFromStringType(paramName);
  }

  public ASTformalParameterSection(int id) {
    super(id);
  }

  public ASTformalParameterSection(MyGrammar p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MyGrammarVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=76a147cbe8ea599c23b06873e9c4feba (do not edit this line) */
