/* Generated By:JJTree: Do not edit this line. ASTformalParameterList.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package main.jjtree;

public
class ASTformalParameterList extends SimpleNode {
  public ASTformalParameterList(int id) {
    super(id);
  }

  public ASTformalParameterList(MyGrammar p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MyGrammarVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=70e41ca3c05463ecf134d2789e396d65 (do not edit this line) */
