/* Generated By:JJTree: Do not edit this line. ASTfunctionDeclaration.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package main.jjtree;

public
class ASTfunctionDeclaration extends SimpleNode {
  public ASTfunctionDeclaration(int id) {
    super(id);
  }

  public ASTfunctionDeclaration(MyGrammar p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MyGrammarVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=acdf27ab17315edd23fb6c79d96e1d00 (do not edit this line) */
