/* Generated By:JJTree: Do not edit this line. ASTfunctionBody.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package main.jjtree;

public
class ASTfunctionBody extends SimpleNode {
  public ASTfunctionBody(int id) {
    super(id);
  }

  public ASTfunctionBody(MyGrammar p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MyGrammarVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=e2856dc66fb5571953a7de4d6710d1e9 (do not edit this line) */
