/* Generated By:JJTree: Do not edit this line. ASTfunctionCall.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package main.jjtree;

import main.SymbolTable;

public
class ASTfunctionCall extends SimpleNode {

    public String name;

    public ASTfunctionCall(int id) {
        super(id);
    }

    public ASTfunctionCall(MyGrammar p, int id) {
        super(p, id);
    }

    public int getFunctionReturnType() {
        // will throw if function undeclared
        return SymbolTable.symbolTable.getFunction(name).heading.returnType;
    }

    /**
     * Accept the visitor.
     **/
    public Object jjtAccept(MyGrammarVisitor visitor, Object data) {

        return visitor.visit(this, data);
    }
}
/* JavaCC - OriginalChecksum=63b82621a69c10b5bc4493e95a0bd651 (do not edit this line) */
