/* Generated By:JJTree: Do not edit this line. ASTformalParameterList.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package main.jjtree;

public
class ASTformalParameterList extends SimpleNode {
  public ASTformalParameterList(int id) {
    super(id);
  }

  public ASTformalParameterList(MyGrammar p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MyGrammarVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=c0e7769c413eed4a7a7dc3f133ca8e00 (do not edit this line) */
