/* Generated By:JJTree: Do not edit this line. ASTidentifierList.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package main.jjtree;

public
class ASTidentifierList extends SimpleNode {
  public ASTidentifierList(int id) {
    super(id);
  }

  public ASTidentifierList(MyGrammar p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MyGrammarVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=486adb103b49f1f8f5546d6315e53f13 (do not edit this line) */
