/* Generated By:JJTree: Do not edit this line. ASTidentifierList.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package main.jjtree;

public
class ASTidentifierList extends SimpleNode {
  public ASTidentifierList(int id) {
    super(id);
  }

  public ASTidentifierList(MyGrammar p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MyGrammarVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=568ed2efa11861ea6cc5dacb44187080 (do not edit this line) */
