/* Generated By:JJTree: Do not edit this line. ASTprocedureBody.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package main.jjtree;

public
class ASTprocedureBody extends SimpleNode {
  public ASTprocedureBody(int id) {
    super(id);
  }

  public ASTprocedureBody(MyGrammar p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MyGrammarVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=6a497e6618d6c570681afed4d0259030 (do not edit this line) */
