/* Generated By:JJTree: Do not edit this line. ASTprocedureCall.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package main.jjtree;

public
class ASTprocedureCall extends SimpleNode {
  public String name;
  public ASTprocedureCall(int id) {
    super(id);
  }

  public ASTprocedureCall(MyGrammar p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MyGrammarVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=6e449d21c2140fdbbc243a5775c395cf (do not edit this line) */
