/* Generated By:JJTree: Do not edit this line. ASTprocedureIdentifier.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package main.jjtree;

public
class ASTprocedureIdentifier extends SimpleNode {
  public ASTprocedureIdentifier(int id) {
    super(id);
  }

  public ASTprocedureIdentifier(MyGrammar p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MyGrammarVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=f6c47bcbd914bd2557f16335669c9f44 (do not edit this line) */
