/* Generated By:JJTree: Do not edit this line. ASTReadIntCall.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package main.jjtree;

import main.Exceptions.RuntimeError;

import java.util.InputMismatchException;
import java.util.Scanner;

public
class ASTReadIntCall extends ASTbuiltInCalls {

    @Override
    public int getReturnType() {
        return 0;
    }

    public ASTReadIntCall(int id) {
        super(id);
    }

    public ASTReadIntCall(MyGrammar p, int id) {
        super(p, id);
    }


    /**
     * Accept the visitor.
     **/
    public Object jjtAccept(MyGrammarVisitor visitor, Object data) {
        Scanner scanner = new Scanner(System.in);
        while (true) {
            try {
                return scanner.nextInt(); // Attempt to read an integer
            } catch (InputMismatchException e) {
                System.out.println("That's not an integer. Please try again.");
                scanner.nextLine(); // Clear the invalid input
            }
        }
    }
}
/* JavaCC - OriginalChecksum=84e66de5f8e4435f944a7df8eda60441 (do not edit this line) */
