/* Generated By:JJTree: Do not edit this line. ASTstatementSequence.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package main.jjtree;

public
class ASTstatementSequence extends SimpleNode {
  public ASTstatementSequence(int id) {
    super(id);
  }

  public ASTstatementSequence(MyGrammar p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MyGrammarVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=bd12ec2d316eaf4456eb1e9fdbca797a (do not edit this line) */
