/* Generated By:JJTree: Do not edit this line. ASTsimpleStatement.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package main.jjtree;

public
class ASTsimpleStatement extends SimpleNode {
  public ASTsimpleStatement(int id) {
    super(id);
  }

  public ASTsimpleStatement(MyGrammar p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MyGrammarVisitor visitor, Object data) {

    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=c2f0d0caa32555929626d56f369b6921 (do not edit this line) */
