/* Generated By:JJTree: Do not edit this line. ASTUnaryExpression.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package main.jjtree;

public
class ASTUnaryExpression extends ASTExpression {
  public ASTUnaryExpression(int id) {
    super(id);
  }

  public ASTUnaryExpression(MyGrammar p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MyGrammarVisitor visitor, Object data) {
    return execute(visitor, data);
  }
}
/* JavaCC - OriginalChecksum=8e4358a9cdfbbce24b2d551d0014deea (do not edit this line) */
