/* Generated By:JJTree: Do not edit this line. ASTvariableDeclarationPart.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package main.jjtree;

public
class ASTvariableDeclarationPart extends SimpleNode {
  public ASTvariableDeclarationPart(int id) {
    super(id);
  }

  public ASTvariableDeclarationPart(MyGrammar p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MyGrammarVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=f94fb96f41e65326a5e360a53d019588 (do not edit this line) */
