/* Generated By:JJTree: Do not edit this line. ASTvariableIdentifier.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package main.jjtree;

public
class ASTvariableIdentifier extends SimpleNode {
  public ASTvariableIdentifier(int id) {
    super(id);
  }

  public ASTvariableIdentifier(MyGrammar p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MyGrammarVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=031de16c7dac7a3a944e669c2f87a65d (do not edit this line) */
