/* Generated By:JJTree&JavaCC: Do not edit this line. MyGrammarConstants.java */
package main.jjtree;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface MyGrammarConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SINGLECOM = 7;
  /** RegularExpression Id. */
  int MULTCOM = 8;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT = 9;
  /** RegularExpression Id. */
  int MULTI_LINE_COMMENT = 10;
  /** RegularExpression Id. */
  int MINLETTER = 11;
  /** RegularExpression Id. */
  int CAPLETTER = 12;
  /** RegularExpression Id. */
  int DIGIT = 13;
  /** RegularExpression Id. */
  int INT = 14;
  /** RegularExpression Id. */
  int REAL = 15;
  /** RegularExpression Id. */
  int BOOL = 16;
  /** RegularExpression Id. */
  int INT_KEYWORD = 17;
  /** RegularExpression Id. */
  int REAL_KEYWORD = 18;
  /** RegularExpression Id. */
  int STRING_KEYWORD = 19;
  /** RegularExpression Id. */
  int BOOL_KEYWORD = 20;
  /** RegularExpression Id. */
  int PROGRAM = 21;
  /** RegularExpression Id. */
  int FUNCTION = 22;
  /** RegularExpression Id. */
  int PROCEDURE = 23;
  /** RegularExpression Id. */
  int VAR = 24;
  /** RegularExpression Id. */
  int BEGIN = 25;
  /** RegularExpression Id. */
  int END = 26;
  /** RegularExpression Id. */
  int WHILE = 27;
  /** RegularExpression Id. */
  int BREAK = 28;
  /** RegularExpression Id. */
  int DO = 29;
  /** RegularExpression Id. */
  int IF = 30;
  /** RegularExpression Id. */
  int THEN = 31;
  /** RegularExpression Id. */
  int ELSE = 32;
  /** RegularExpression Id. */
  int RESULT = 33;
  /** RegularExpression Id. */
  int PRINT = 34;
  /** RegularExpression Id. */
  int NOT = 35;
  /** RegularExpression Id. */
  int OR = 36;
  /** RegularExpression Id. */
  int AND = 37;
  /** RegularExpression Id. */
  int PLUS = 38;
  /** RegularExpression Id. */
  int MINUS = 39;
  /** RegularExpression Id. */
  int MULTIPLY = 40;
  /** RegularExpression Id. */
  int DIVIDE = 41;
  /** RegularExpression Id. */
  int LESS = 42;
  /** RegularExpression Id. */
  int GREATER = 43;
  /** RegularExpression Id. */
  int LESSEQUAL = 44;
  /** RegularExpression Id. */
  int GREATEREQUAL = 45;
  /** RegularExpression Id. */
  int EQUAL = 46;
  /** RegularExpression Id. */
  int NOTEQUAL = 47;
  /** RegularExpression Id. */
  int ASSIGN = 48;
  /** RegularExpression Id. */
  int LPAREN = 49;
  /** RegularExpression Id. */
  int RPAREN = 50;
  /** RegularExpression Id. */
  int COMMA = 51;
  /** RegularExpression Id. */
  int COLON = 52;
  /** RegularExpression Id. */
  int SEMICOLON = 53;
  /** RegularExpression Id. */
  int IDENTIFIER = 54;
  /** RegularExpression Id. */
  int STRING = 55;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\\' \\\'\"",
    "\"\\\'\\\'\"",
    "<SINGLECOM>",
    "<MULTCOM>",
    "<SINGLE_LINE_COMMENT>",
    "<MULTI_LINE_COMMENT>",
    "<MINLETTER>",
    "<CAPLETTER>",
    "<DIGIT>",
    "<INT>",
    "<REAL>",
    "<BOOL>",
    "\"int\"",
    "\"real\"",
    "\"string\"",
    "\"bool\"",
    "\"program\"",
    "\"function\"",
    "\"procedure\"",
    "\"var\"",
    "\"begin\"",
    "\"end\"",
    "\"while\"",
    "\"break\"",
    "\"do\"",
    "\"if\"",
    "\"then\"",
    "\"else\"",
    "\"Result\"",
    "\"print\"",
    "\"!\"",
    "\"||\"",
    "\"&&\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"<\"",
    "\">\"",
    "\"<=\"",
    "\">=\"",
    "\"==\"",
    "\"!=\"",
    "\":=\"",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\":\"",
    "\";\"",
    "<IDENTIFIER>",
    "<STRING>",
  };

}
