/* MyGrammar.java */
/* Generated By:JJTree&JavaCC: Do not edit this line. MyGrammar.java */
package main.jjtree;
import java.io.FileReader;
import main.*;


enum ExpType {
    Number,Boolean,FunctionCall,Variable
}

public class MyGrammar/*@bgen(jjtree)*/implements MyGrammarTreeConstants, MyGrammarConstants {/*@bgen(jjtree)*/
  protected JJTMyGrammarState jjtree = new JJTMyGrammarState();


    public static void main(String args[]) {
        if (args.length != 1) {
            System.out.println("Usage: java MyGrammar <filename>");
            return;
        }

        String filename = args[0];
        try {
            FileReader fileReader = new FileReader(filename);
            MyGrammar parser = new MyGrammar(fileReader);
            parser.enable_tracing();

            SimpleNode rootNode = parser.Start();
             DotGenerator generator = new DotGenerator();
             generator.generateDot(rootNode);
             generator.getDotGraph();





            SemanticAnalysisVisitor visitor = new SemanticAnalysisVisitor();
            rootNode.jjtAccept(visitor, null); // Starts the visiting process*/





            System.out.println("File parsed successfully.");
        } catch (TokenMgrError e) {
            System.out.println("Lexical Error: \n" + e.getMessage());
        } catch (ParseException e) {
            System.out.println("Syntax Error: \n" + e.getMessage());
            System.out.println(e.currentToken.next.kind);
            //System.out.println(e.);
        } catch ( Throwable t) {
            System.out.println("other error:");
            t.printStackTrace();
        }
    }

// High-level structure
  final public SimpleNode Start() throws ParseException {/*@bgen(jjtree) Start */
  ASTStart jjtn000 = new ASTStart(JJTSTART);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      programHeading();
      label_1:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case FUNCTION:{
          ;
          break;
          }
        default:
          jj_la1[0] = jj_gen;
          break label_1;
        }
        functionDeclaration();
      }
      label_2:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case PROCEDURE:{
          ;
          break;
          }
        default:
          jj_la1[1] = jj_gen;
          break label_2;
        }
        procedureDeclaration();
      }
      block();
jjtree.closeNodeScope(jjtn000, true);
       jjtc000 = false;
{if ("" != null) return jjtn000;}
    } catch (Throwable jjte000) {
if (jjtc000) {
        jjtree.clearNodeScope(jjtn000);
        jjtc000 = false;
      } else {
        jjtree.popNode();
      }
      if (jjte000 instanceof RuntimeException) {
        {if (true) throw (RuntimeException)jjte000;}
      }
      if (jjte000 instanceof ParseException) {
        {if (true) throw (ParseException)jjte000;}
      }
      {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
    throw new Error("Missing return statement in function");
}

  final public void programHeading() throws ParseException {/*@bgen(jjtree) programHeading */
  ASTprogramHeading jjtn000 = new ASTprogramHeading(JJTPROGRAMHEADING);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(PROGRAM);
      identifier();
    } catch (Throwable jjte000) {
if (jjtc000) {
        jjtree.clearNodeScope(jjtn000);
        jjtc000 = false;
      } else {
        jjtree.popNode();
      }
      if (jjte000 instanceof RuntimeException) {
        {if (true) throw (RuntimeException)jjte000;}
      }
      if (jjte000 instanceof ParseException) {
        {if (true) throw (ParseException)jjte000;}
      }
      {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
}

// Function-related rules
  final public void functionDeclaration() throws ParseException {/*@bgen(jjtree) functionDeclaration */
  ASTfunctionDeclaration jjtn000 = new ASTfunctionDeclaration(JJTFUNCTIONDECLARATION);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      functionHeading();
      functionBody();
    } catch (Throwable jjte000) {
if (jjtc000) {
        jjtree.clearNodeScope(jjtn000);
        jjtc000 = false;
      } else {
        jjtree.popNode();
      }
      if (jjte000 instanceof RuntimeException) {
        {if (true) throw (RuntimeException)jjte000;}
      }
      if (jjte000 instanceof ParseException) {
        {if (true) throw (ParseException)jjte000;}
      }
      {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
}

  final public void functionHeading() throws ParseException {/*@bgen(jjtree) functionHeading */
 ASTfunctionHeading jjtn000 = new ASTfunctionHeading(JJTFUNCTIONHEADING);
 boolean jjtc000 = true;
 jjtree.openNodeScope(jjtn000);Token functionName,returnType;
    try {
      jj_consume_token(FUNCTION);
      functionName = identifier();
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case LPAREN:{
        formalParameterList();
        break;
        }
      default:
        jj_la1[2] = jj_gen;
        ;
      }
      jj_consume_token(COLON);
      returnType = typeIdentifier();
jjtree.closeNodeScope(jjtn000, true);
      jjtc000 = false;
jjtn000.functionName = functionName.image;
        jjtn000.returnType = returnType.image;
    } catch (Throwable jjte000) {
if (jjtc000) {
        jjtree.clearNodeScope(jjtn000);
        jjtc000 = false;
      } else {
        jjtree.popNode();
      }
      if (jjte000 instanceof RuntimeException) {
        {if (true) throw (RuntimeException)jjte000;}
      }
      if (jjte000 instanceof ParseException) {
        {if (true) throw (ParseException)jjte000;}
      }
      {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
}

  final public void functionBody() throws ParseException {/*@bgen(jjtree) functionBody */
  ASTfunctionBody jjtn000 = new ASTfunctionBody(JJTFUNCTIONBODY);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      block();
    } catch (Throwable jjte000) {
if (jjtc000) {
        jjtree.clearNodeScope(jjtn000);
        jjtc000 = false;
      } else {
        jjtree.popNode();
      }
      if (jjte000 instanceof RuntimeException) {
        {if (true) throw (RuntimeException)jjte000;}
      }
      if (jjte000 instanceof ParseException) {
        {if (true) throw (ParseException)jjte000;}
      }
      {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
}

  final public void formalParameterList() throws ParseException {/*@bgen(jjtree) formalParameterList */
  ASTformalParameterList jjtn000 = new ASTformalParameterList(JJTFORMALPARAMETERLIST);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(LPAREN);
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case IDENTIFIER:{
        formalParameterSection();
        break;
        }
      default:
        jj_la1[3] = jj_gen;
        ;
      }
      label_3:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case COMMA:{
          ;
          break;
          }
        default:
          jj_la1[4] = jj_gen;
          break label_3;
        }
        jj_consume_token(COMMA);
        formalParameterSection();
      }
      jj_consume_token(RPAREN);
    } catch (Throwable jjte000) {
if (jjtc000) {
        jjtree.clearNodeScope(jjtn000);
        jjtc000 = false;
      } else {
        jjtree.popNode();
      }
      if (jjte000 instanceof RuntimeException) {
        {if (true) throw (RuntimeException)jjte000;}
      }
      if (jjte000 instanceof ParseException) {
        {if (true) throw (ParseException)jjte000;}
      }
      {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
}

  final public void formalParameterSection() throws ParseException {/*@bgen(jjtree) formalParameterSection */
 ASTformalParameterSection jjtn000 = new ASTformalParameterSection(JJTFORMALPARAMETERSECTION);
 boolean jjtc000 = true;
 jjtree.openNodeScope(jjtn000);Token paramName, paramType;
    try {
      paramName = identifier();
      jj_consume_token(COLON);
      paramType = typeIdentifier();
jjtree.closeNodeScope(jjtn000, true);
      jjtc000 = false;
jjtn000.paramType = paramType.image;
        jjtn000.paramName = paramName.image;
    } catch (Throwable jjte000) {
if (jjtc000) {
        jjtree.clearNodeScope(jjtn000);
        jjtc000 = false;
      } else {
        jjtree.popNode();
      }
      if (jjte000 instanceof RuntimeException) {
        {if (true) throw (RuntimeException)jjte000;}
      }
      if (jjte000 instanceof ParseException) {
        {if (true) throw (ParseException)jjte000;}
      }
      {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
}

// Procedure-related rules
  final public void procedureDeclaration() throws ParseException {/*@bgen(jjtree) procedureDeclaration */
  ASTprocedureDeclaration jjtn000 = new ASTprocedureDeclaration(JJTPROCEDUREDECLARATION);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      procedureHeading();
      procedureBody();
    } catch (Throwable jjte000) {
if (jjtc000) {
        jjtree.clearNodeScope(jjtn000);
        jjtc000 = false;
      } else {
        jjtree.popNode();
      }
      if (jjte000 instanceof RuntimeException) {
        {if (true) throw (RuntimeException)jjte000;}
      }
      if (jjte000 instanceof ParseException) {
        {if (true) throw (ParseException)jjte000;}
      }
      {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
}

  final public void procedureHeading() throws ParseException {/*@bgen(jjtree) procedureHeading */
 ASTprocedureHeading jjtn000 = new ASTprocedureHeading(JJTPROCEDUREHEADING);
 boolean jjtc000 = true;
 jjtree.openNodeScope(jjtn000);Token name;
    try {
      jj_consume_token(PROCEDURE);
      name = identifier();
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case LPAREN:{
        formalParameterList();
        break;
        }
      default:
        jj_la1[5] = jj_gen;
        ;
      }
jjtree.closeNodeScope(jjtn000, true);
      jjtc000 = false;
jjtn000.name = name.image;
    } catch (Throwable jjte000) {
if (jjtc000) {
        jjtree.clearNodeScope(jjtn000);
        jjtc000 = false;
      } else {
        jjtree.popNode();
      }
      if (jjte000 instanceof RuntimeException) {
        {if (true) throw (RuntimeException)jjte000;}
      }
      if (jjte000 instanceof ParseException) {
        {if (true) throw (ParseException)jjte000;}
      }
      {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
}

  final public void procedureBody() throws ParseException {/*@bgen(jjtree) procedureBody */
  ASTprocedureBody jjtn000 = new ASTprocedureBody(JJTPROCEDUREBODY);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      block();
    } catch (Throwable jjte000) {
if (jjtc000) {
        jjtree.clearNodeScope(jjtn000);
        jjtc000 = false;
      } else {
        jjtree.popNode();
      }
      if (jjte000 instanceof RuntimeException) {
        {if (true) throw (RuntimeException)jjte000;}
      }
      if (jjte000 instanceof ParseException) {
        {if (true) throw (ParseException)jjte000;}
      }
      {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
}

// Block and statements
  final public void block() throws ParseException {/*@bgen(jjtree) block */
  ASTblock jjtn000 = new ASTblock(JJTBLOCK);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case VAR:{
        variableDeclarationPart();
        break;
        }
      default:
        jj_la1[6] = jj_gen;
        ;
      }
      statementPart();
    } catch (Throwable jjte000) {
if (jjtc000) {
        jjtree.clearNodeScope(jjtn000);
        jjtc000 = false;
      } else {
        jjtree.popNode();
      }
      if (jjte000 instanceof RuntimeException) {
        {if (true) throw (RuntimeException)jjte000;}
      }
      if (jjte000 instanceof ParseException) {
        {if (true) throw (ParseException)jjte000;}
      }
      {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
}

  final public void variableDeclarationPart() throws ParseException {/*@bgen(jjtree) variableDeclarationPart */
  ASTvariableDeclarationPart jjtn000 = new ASTvariableDeclarationPart(JJTVARIABLEDECLARATIONPART);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(VAR);
      variableDeclaration();
      jj_consume_token(SEMICOLON);
      label_4:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case IDENTIFIER:{
          ;
          break;
          }
        default:
          jj_la1[7] = jj_gen;
          break label_4;
        }
        variableDeclaration();
        jj_consume_token(SEMICOLON);
      }
    } catch (Throwable jjte000) {
if (jjtc000) {
        jjtree.clearNodeScope(jjtn000);
        jjtc000 = false;
      } else {
        jjtree.popNode();
      }
      if (jjte000 instanceof RuntimeException) {
        {if (true) throw (RuntimeException)jjte000;}
      }
      if (jjte000 instanceof ParseException) {
        {if (true) throw (ParseException)jjte000;}
      }
      {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
}

  final public void variableDeclaration() throws ParseException {/*@bgen(jjtree) variableDeclaration */
 ASTvariableDeclaration jjtn000 = new ASTvariableDeclaration(JJTVARIABLEDECLARATION);
 boolean jjtc000 = true;
 jjtree.openNodeScope(jjtn000);Token varName,varType;
    try {
      varName = identifier();
      jj_consume_token(COLON);
      varType = typeIdentifier();
jjtree.closeNodeScope(jjtn000, true);
      jjtc000 = false;
jjtn000.name= varName.image; jjtn000.type=varType.image;
    } catch (Throwable jjte000) {
if (jjtc000) {
        jjtree.clearNodeScope(jjtn000);
        jjtc000 = false;
      } else {
        jjtree.popNode();
      }
      if (jjte000 instanceof RuntimeException) {
        {if (true) throw (RuntimeException)jjte000;}
      }
      if (jjte000 instanceof ParseException) {
        {if (true) throw (ParseException)jjte000;}
      }
      {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
}

  final public void statementPart() throws ParseException {/*@bgen(jjtree) statementPart */
  ASTstatementPart jjtn000 = new ASTstatementPart(JJTSTATEMENTPART);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(BEGIN);
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case WHILE:
      case IF:
      case IDENTIFIER:{
        statementSequence();
        break;
        }
      default:
        jj_la1[8] = jj_gen;
        ;
      }
      jj_consume_token(END);
    } catch (Throwable jjte000) {
if (jjtc000) {
        jjtree.clearNodeScope(jjtn000);
        jjtc000 = false;
      } else {
        jjtree.popNode();
      }
      if (jjte000 instanceof RuntimeException) {
        {if (true) throw (RuntimeException)jjte000;}
      }
      if (jjte000 instanceof ParseException) {
        {if (true) throw (ParseException)jjte000;}
      }
      {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
}

  final public void statementSequence() throws ParseException {/*@bgen(jjtree) statementSequence */
  ASTstatementSequence jjtn000 = new ASTstatementSequence(JJTSTATEMENTSEQUENCE);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      statement();
      label_5:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case WHILE:
        case IF:
        case IDENTIFIER:{
          ;
          break;
          }
        default:
          jj_la1[9] = jj_gen;
          break label_5;
        }
        statement();
      }
    } catch (Throwable jjte000) {
if (jjtc000) {
        jjtree.clearNodeScope(jjtn000);
        jjtc000 = false;
      } else {
        jjtree.popNode();
      }
      if (jjte000 instanceof RuntimeException) {
        {if (true) throw (RuntimeException)jjte000;}
      }
      if (jjte000 instanceof ParseException) {
        {if (true) throw (ParseException)jjte000;}
      }
      {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
}

  final public void statement() throws ParseException {/*@bgen(jjtree) statement */
  ASTstatement jjtn000 = new ASTstatement(JJTSTATEMENT);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case IDENTIFIER:{
        simpleStatement();
        break;
        }
      case WHILE:
      case IF:{
        structuredStatement();
        break;
        }
      default:
        jj_la1[10] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    } catch (Throwable jjte000) {
if (jjtc000) {
        jjtree.clearNodeScope(jjtn000);
        jjtc000 = false;
      } else {
        jjtree.popNode();
      }
      if (jjte000 instanceof RuntimeException) {
        {if (true) throw (RuntimeException)jjte000;}
      }
      if (jjte000 instanceof ParseException) {
        {if (true) throw (ParseException)jjte000;}
      }
      {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
}

  final public void simpleStatement() throws ParseException {/*@bgen(jjtree) simpleStatement */
  ASTsimpleStatement jjtn000 = new ASTsimpleStatement(JJTSIMPLESTATEMENT);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      if (jj_2_1(3)) {
        assignmentStatement();
        jj_consume_token(SEMICOLON);
      } else {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case IDENTIFIER:{
          procedureCall();
          jj_consume_token(SEMICOLON);
          break;
          }
        default:
          jj_la1[11] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
      }
    } catch (Throwable jjte000) {
if (jjtc000) {
        jjtree.clearNodeScope(jjtn000);
        jjtc000 = false;
      } else {
        jjtree.popNode();
      }
      if (jjte000 instanceof RuntimeException) {
        {if (true) throw (RuntimeException)jjte000;}
      }
      if (jjte000 instanceof ParseException) {
        {if (true) throw (ParseException)jjte000;}
      }
      {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
}

  final public void assignmentStatement() throws ParseException {/*@bgen(jjtree) assignmentStatement */
                              ASTassignmentStatement jjtn000 = new ASTassignmentStatement(JJTASSIGNMENTSTATEMENT);
                              boolean jjtc000 = true;
                              jjtree.openNodeScope(jjtn000);String variableName; String expressionType="string";
    try {
      variableName = variableIdentifier();
      jj_consume_token(ASSIGN);
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case NUMBER:
      case TRUE:
      case FALSE:
      case NOT:
      case IDENTIFIER:
      case LPAREN:
      case MINUS:{
        expression();
        break;
        }
      case STRING:{
        jj_consume_token(STRING);
        break;
        }
      default:
        jj_la1[12] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
jjtree.closeNodeScope(jjtn000, true);
     jjtc000 = false;
jjtn000.variableName = variableName; jjtn000.expressionType = expressionType;
    } catch (Throwable jjte000) {
if (jjtc000) {
       jjtree.clearNodeScope(jjtn000);
       jjtc000 = false;
     } else {
       jjtree.popNode();
     }
     if (jjte000 instanceof RuntimeException) {
       {if (true) throw (RuntimeException)jjte000;}
     }
     if (jjte000 instanceof ParseException) {
       {if (true) throw (ParseException)jjte000;}
     }
     {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
       jjtree.closeNodeScope(jjtn000, true);
     }
    }
}

  final public void procedureCall() throws ParseException {/*@bgen(jjtree) procedureCall */
                       ASTprocedureCall jjtn000 = new ASTprocedureCall(JJTPROCEDURECALL);
                       boolean jjtc000 = true;
                       jjtree.openNodeScope(jjtn000);Token id;
    try {
      id = identifier();
      actualParameterList();
jjtree.closeNodeScope(jjtn000, true);
     jjtc000 = false;
jjtn000.name = id.image;
    } catch (Throwable jjte000) {
if (jjtc000) {
        jjtree.clearNodeScope(jjtn000);
        jjtc000 = false;
      } else {
        jjtree.popNode();
      }
      if (jjte000 instanceof RuntimeException) {
        {if (true) throw (RuntimeException)jjte000;}
      }
      if (jjte000 instanceof ParseException) {
        {if (true) throw (ParseException)jjte000;}
      }
      {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
}

  final public void structuredStatement() throws ParseException {/*@bgen(jjtree) structuredStatement */
  ASTstructuredStatement jjtn000 = new ASTstructuredStatement(JJTSTRUCTUREDSTATEMENT);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case WHILE:{
        whileStatement();
        break;
        }
      case IF:{
        ifStatement();
        break;
        }
      default:
        jj_la1[13] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    } catch (Throwable jjte000) {
if (jjtc000) {
        jjtree.clearNodeScope(jjtn000);
        jjtc000 = false;
      } else {
        jjtree.popNode();
      }
      if (jjte000 instanceof RuntimeException) {
        {if (true) throw (RuntimeException)jjte000;}
      }
      if (jjte000 instanceof ParseException) {
        {if (true) throw (ParseException)jjte000;}
      }
      {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
}

  final public void whileStatement() throws ParseException {/*@bgen(jjtree) whileStatement */
  ASTwhileStatement jjtn000 = new ASTwhileStatement(JJTWHILESTATEMENT);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(WHILE);
      boolExp();
      jj_consume_token(DO);
      statementPart();
    } catch (Throwable jjte000) {
if (jjtc000) {
        jjtree.clearNodeScope(jjtn000);
        jjtc000 = false;
      } else {
        jjtree.popNode();
      }
      if (jjte000 instanceof RuntimeException) {
        {if (true) throw (RuntimeException)jjte000;}
      }
      if (jjte000 instanceof ParseException) {
        {if (true) throw (ParseException)jjte000;}
      }
      {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
}

  final public void ifStatement() throws ParseException {/*@bgen(jjtree) ifStatement */
  ASTifStatement jjtn000 = new ASTifStatement(JJTIFSTATEMENT);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(IF);
      boolExp();
      jj_consume_token(THEN);
      statementPart();
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case ELSE:{
        jj_consume_token(ELSE);
        statementPart();
        break;
        }
      default:
        jj_la1[14] = jj_gen;
        ;
      }
    } catch (Throwable jjte000) {
if (jjtc000) {
        jjtree.clearNodeScope(jjtn000);
        jjtc000 = false;
      } else {
        jjtree.popNode();
      }
      if (jjte000 instanceof RuntimeException) {
        {if (true) throw (RuntimeException)jjte000;}
      }
      if (jjte000 instanceof ParseException) {
        {if (true) throw (ParseException)jjte000;}
      }
      {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
}

// Helper methods for identifiers and types
  final public void identifierList() throws ParseException {/*@bgen(jjtree) identifierList */
  ASTidentifierList jjtn000 = new ASTidentifierList(JJTIDENTIFIERLIST);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      identifier();
      label_6:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case COMMA:{
          ;
          break;
          }
        default:
          jj_la1[15] = jj_gen;
          break label_6;
        }
        jj_consume_token(COMMA);
        identifier();
      }
    } catch (Throwable jjte000) {
if (jjtc000) {
        jjtree.clearNodeScope(jjtn000);
        jjtc000 = false;
      } else {
        jjtree.popNode();
      }
      if (jjte000 instanceof RuntimeException) {
        {if (true) throw (RuntimeException)jjte000;}
      }
      if (jjte000 instanceof ParseException) {
        {if (true) throw (ParseException)jjte000;}
      }
      {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
}

  final public Token typeIdentifier() throws ParseException {/*@bgen(jjtree) typeIdentifier */
  ASTtypeIdentifier jjtn000 = new ASTtypeIdentifier(JJTTYPEIDENTIFIER);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);Token t = null;
    try {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case NUMBER_KEYWORD:{
        t = jj_consume_token(NUMBER_KEYWORD);
jjtree.closeNodeScope(jjtn000, true);
                           jjtc000 = false;
{if ("" != null) return t;}
        break;
        }
      case STRING_KEYWORD:{
        t = jj_consume_token(STRING_KEYWORD);
jjtree.closeNodeScope(jjtn000, true);
                           jjtc000 = false;
{if ("" != null) return t;}
        break;
        }
      case BOOL_KEYWORD:{
        t = jj_consume_token(BOOL_KEYWORD);
jjtree.closeNodeScope(jjtn000, true);
                         jjtc000 = false;
{if ("" != null) return t;}
        break;
        }
      default:
        jj_la1[16] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    } finally {
if (jjtc000) {
       jjtree.closeNodeScope(jjtn000, true);
     }
    }
    throw new Error("Missing return statement in function");
}

  final public Token identifier() throws ParseException {/*@bgen(jjtree) identifier */
 ASTidentifier jjtn000 = new ASTidentifier(JJTIDENTIFIER);
 boolean jjtc000 = true;
 jjtree.openNodeScope(jjtn000);Token t ;
    try {
      t = jj_consume_token(IDENTIFIER);
jjtree.closeNodeScope(jjtn000, true);
                       jjtc000 = false;
{if ("" != null) return t;}
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
    throw new Error("Missing return statement in function");
}

  final public String variableIdentifier() throws ParseException {/*@bgen(jjtree) variableIdentifier */
 ASTvariableIdentifier jjtn000 = new ASTvariableIdentifier(JJTVARIABLEIDENTIFIER);
 boolean jjtc000 = true;
 jjtree.openNodeScope(jjtn000);Token t;
    try {
      t = identifier();
jjtree.closeNodeScope(jjtn000, true);
                     jjtc000 = false;
{if ("" != null) return t.image;}
    } catch (Throwable jjte000) {
if (jjtc000) {
        jjtree.clearNodeScope(jjtn000);
        jjtc000 = false;
      } else {
        jjtree.popNode();
      }
      if (jjte000 instanceof RuntimeException) {
        {if (true) throw (RuntimeException)jjte000;}
      }
      if (jjte000 instanceof ParseException) {
        {if (true) throw (ParseException)jjte000;}
      }
      {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
    throw new Error("Missing return statement in function");
}

// Expression
  final public void expression() throws ParseException {/*@bgen(jjtree) expression */
                     ASTexpression jjtn000 = new ASTexpression(JJTEXPRESSION);
                     boolean jjtc000 = true;
                     jjtree.openNodeScope(jjtn000);ExpType type;
    try {
      if (jj_2_2(3)) {
        type = arthExp();
      } else {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case NUMBER:
        case TRUE:
        case FALSE:
        case NOT:
        case IDENTIFIER:
        case LPAREN:
        case MINUS:{
          boolExp();
          break;
          }
        default:
          jj_la1[17] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
      }
    } catch (Throwable jjte000) {
if (jjtc000) {
        jjtree.clearNodeScope(jjtn000);
        jjtc000 = false;
      } else {
        jjtree.popNode();
      }
      if (jjte000 instanceof RuntimeException) {
        {if (true) throw (RuntimeException)jjte000;}
      }
      if (jjte000 instanceof ParseException) {
        {if (true) throw (ParseException)jjte000;}
      }
      {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
}

// Arithmetic Expressions
  final public ExpType arthExp() throws ParseException {/*@bgen(jjtree) arthExp */
 ASTarthExp jjtn000 = new ASTarthExp(JJTARTHEXP);
 boolean jjtc000 = true;
 jjtree.openNodeScope(jjtn000);ExpType type;
    try {
      type = arthTerm();
      arthExpPrime(type);
jjtree.closeNodeScope(jjtn000, true);
                                        jjtc000 = false;
{if ("" != null) return type;}
    } catch (Throwable jjte000) {
if (jjtc000) {
        jjtree.clearNodeScope(jjtn000);
        jjtc000 = false;
      } else {
        jjtree.popNode();
      }
      if (jjte000 instanceof RuntimeException) {
        {if (true) throw (RuntimeException)jjte000;}
      }
      if (jjte000 instanceof ParseException) {
        {if (true) throw (ParseException)jjte000;}
      }
      {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
    throw new Error("Missing return statement in function");
}

  final public void arthExpPrime(ExpType inheritedType) throws ParseException {/*@bgen(jjtree) arthExpPrime */
 ASTarthExpPrime jjtn000 = new ASTarthExpPrime(JJTARTHEXPPRIME);
 boolean jjtc000 = true;
 jjtree.openNodeScope(jjtn000);ExpType type;
    try {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case PLUS:{
        jj_consume_token(PLUS);
        type = arthTerm();
        arthExpPrime(type);
jjtree.closeNodeScope(jjtn000, true);
                                                jjtc000 = false;

        break;
        }
      case MINUS:{
        jj_consume_token(MINUS);
        type = arthTerm();
        arthExpPrime(type);
jjtree.closeNodeScope(jjtn000, true);
                                                   jjtc000 = false;

        break;
        }
      default:
        jj_la1[18] = jj_gen;
jjtree.closeNodeScope(jjtn000, true);
      jjtc000 = false;

      }
    } catch (Throwable jjte000) {
if (jjtc000) {
        jjtree.clearNodeScope(jjtn000);
        jjtc000 = false;
      } else {
        jjtree.popNode();
      }
      if (jjte000 instanceof RuntimeException) {
        {if (true) throw (RuntimeException)jjte000;}
      }
      if (jjte000 instanceof ParseException) {
        {if (true) throw (ParseException)jjte000;}
      }
      {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
}

  final public ExpType arthTerm() throws ParseException {/*@bgen(jjtree) arthTerm */
 ASTarthTerm jjtn000 = new ASTarthTerm(JJTARTHTERM);
 boolean jjtc000 = true;
 jjtree.openNodeScope(jjtn000);ExpType type;
    try {
      type = arthFactor();
      arthTermPrime(type);
jjtree.closeNodeScope(jjtn000, true);
                                              jjtc000 = false;
{if ("" != null) return type;}
    } catch (Throwable jjte000) {
if (jjtc000) {
        jjtree.clearNodeScope(jjtn000);
        jjtc000 = false;
      } else {
        jjtree.popNode();
      }
      if (jjte000 instanceof RuntimeException) {
        {if (true) throw (RuntimeException)jjte000;}
      }
      if (jjte000 instanceof ParseException) {
        {if (true) throw (ParseException)jjte000;}
      }
      {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
    throw new Error("Missing return statement in function");
}

  final public void arthTermPrime(ExpType inheritedType) throws ParseException {/*@bgen(jjtree) arthTermPrime */
 ASTarthTermPrime jjtn000 = new ASTarthTermPrime(JJTARTHTERMPRIME);
 boolean jjtc000 = true;
 jjtree.openNodeScope(jjtn000);ExpType type;
    try {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case MULTIPLY:{
        jj_consume_token(MULTIPLY);
        type = arthFactor();
        arthTermPrime(type);
jjtree.closeNodeScope(jjtn000, true);
                                                         jjtc000 = false;

        break;
        }
      case DIVIDE:{
        jj_consume_token(DIVIDE);
        type = arthFactor();
        arthTermPrime(type);
jjtree.closeNodeScope(jjtn000, true);
                                                       jjtc000 = false;

        break;
        }
      default:
        jj_la1[19] = jj_gen;
jjtree.closeNodeScope(jjtn000, true);
      jjtc000 = false;

      }
    } catch (Throwable jjte000) {
if (jjtc000) {
        jjtree.clearNodeScope(jjtn000);
        jjtc000 = false;
      } else {
        jjtree.popNode();
      }
      if (jjte000 instanceof RuntimeException) {
        {if (true) throw (RuntimeException)jjte000;}
      }
      if (jjte000 instanceof ParseException) {
        {if (true) throw (ParseException)jjte000;}
      }
      {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
}

  final public ExpType arthFactor() throws ParseException {/*@bgen(jjtree) arthFactor */
 ASTarthFactor jjtn000 = new ASTarthFactor(JJTARTHFACTOR);
 boolean jjtc000 = true;
 jjtree.openNodeScope(jjtn000);ExpType type;
    try {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case MINUS:{
        jj_consume_token(MINUS);
        type = numValue();
jjtree.closeNodeScope(jjtn000, true);
                              jjtc000 = false;
{if ("" != null) return type;}
        break;
        }
      case NUMBER:
      case IDENTIFIER:
      case LPAREN:{
        type = numValue();
jjtree.closeNodeScope(jjtn000, true);
                        jjtc000 = false;
{if ("" != null) return type;}
        break;
        }
      default:
        jj_la1[20] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    } catch (Throwable jjte000) {
if (jjtc000) {
        jjtree.clearNodeScope(jjtn000);
        jjtc000 = false;
      } else {
        jjtree.popNode();
      }
      if (jjte000 instanceof RuntimeException) {
        {if (true) throw (RuntimeException)jjte000;}
      }
      if (jjte000 instanceof ParseException) {
        {if (true) throw (ParseException)jjte000;}
      }
      {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
    throw new Error("Missing return statement in function");
}

  final public ExpType numValue() throws ParseException {/*@bgen(jjtree) numValue */
 ASTnumValue jjtn000 = new ASTnumValue(JJTNUMVALUE);
 boolean jjtc000 = true;
 jjtree.openNodeScope(jjtn000);ExpType type;
    try {
      if (jj_2_3(3)) {
        functionCall();
jjtree.closeNodeScope(jjtn000, true);
                                  jjtc000 = false;
{if ("" != null) return ExpType.FunctionCall;}
      } else {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case IDENTIFIER:{
          variableIdentifier();
jjtree.closeNodeScope(jjtn000, true);
                           jjtc000 = false;
{if ("" != null) return ExpType.Variable;}
          break;
          }
        case LPAREN:{
          jj_consume_token(LPAREN);
          type = arthExp();
          jj_consume_token(RPAREN);
jjtree.closeNodeScope(jjtn000, true);
                                         jjtc000 = false;
{if ("" != null) return type;}
          break;
          }
        case NUMBER:{
          number();
jjtree.closeNodeScope(jjtn000, true);
               jjtc000 = false;
{if ("" != null) return ExpType.Number;}
          break;
          }
        default:
          jj_la1[21] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
      }
    } catch (Throwable jjte000) {
if (jjtc000) {
        jjtree.clearNodeScope(jjtn000);
        jjtc000 = false;
      } else {
        jjtree.popNode();
      }
      if (jjte000 instanceof RuntimeException) {
        {if (true) throw (RuntimeException)jjte000;}
      }
      if (jjte000 instanceof ParseException) {
        {if (true) throw (ParseException)jjte000;}
      }
      {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
    throw new Error("Missing return statement in function");
}

  final public String number() throws ParseException {/*@bgen(jjtree) number */
                   ASTnumber jjtn000 = new ASTnumber(JJTNUMBER);
                   boolean jjtc000 = true;
                   jjtree.openNodeScope(jjtn000);String type;
    try {
      jj_consume_token(NUMBER);
type="number";
jjtree.closeNodeScope(jjtn000, true);
      jjtc000 = false;
{if ("" != null) return type;}
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
    throw new Error("Missing return statement in function");
}

// Boolean Expressions
  final public ExpType boolExp() throws ParseException {/*@bgen(jjtree) boolExp */
 ASTboolExp jjtn000 = new ASTboolExp(JJTBOOLEXP);
 boolean jjtc000 = true;
 jjtree.openNodeScope(jjtn000);ExpType type;
    try {
      type = boolTerm();
      boolExpPrime(type);
jjtree.closeNodeScope(jjtn000, true);
                                        jjtc000 = false;
{if ("" != null) return type;}
    } catch (Throwable jjte000) {
if (jjtc000) {
        jjtree.clearNodeScope(jjtn000);
        jjtc000 = false;
      } else {
        jjtree.popNode();
      }
      if (jjte000 instanceof RuntimeException) {
        {if (true) throw (RuntimeException)jjte000;}
      }
      if (jjte000 instanceof ParseException) {
        {if (true) throw (ParseException)jjte000;}
      }
      {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
    throw new Error("Missing return statement in function");
}

  final public void boolExpPrime(ExpType inheritedType) throws ParseException {/*@bgen(jjtree) boolExpPrime */
 ASTboolExpPrime jjtn000 = new ASTboolExpPrime(JJTBOOLEXPPRIME);
 boolean jjtc000 = true;
 jjtree.openNodeScope(jjtn000);ExpType type;
    try {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case OR:{
        jj_consume_token(OR);
        type = boolTerm();
        boolExpPrime(type);
        break;
        }
      default:
        jj_la1[22] = jj_gen;
jjtree.closeNodeScope(jjtn000, true);
      jjtc000 = false;

      }
    } catch (Throwable jjte000) {
if (jjtc000) {
        jjtree.clearNodeScope(jjtn000);
        jjtc000 = false;
      } else {
        jjtree.popNode();
      }
      if (jjte000 instanceof RuntimeException) {
        {if (true) throw (RuntimeException)jjte000;}
      }
      if (jjte000 instanceof ParseException) {
        {if (true) throw (ParseException)jjte000;}
      }
      {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
}

  final public ExpType boolTerm() throws ParseException {/*@bgen(jjtree) boolTerm */
 ASTboolTerm jjtn000 = new ASTboolTerm(JJTBOOLTERM);
 boolean jjtc000 = true;
 jjtree.openNodeScope(jjtn000);ExpType type;
    try {
      type = boolFactor();
      boolTermPrime(type);
jjtree.closeNodeScope(jjtn000, true);
                                              jjtc000 = false;
{if ("" != null) return type;}
    } catch (Throwable jjte000) {
if (jjtc000) {
        jjtree.clearNodeScope(jjtn000);
        jjtc000 = false;
      } else {
        jjtree.popNode();
      }
      if (jjte000 instanceof RuntimeException) {
        {if (true) throw (RuntimeException)jjte000;}
      }
      if (jjte000 instanceof ParseException) {
        {if (true) throw (ParseException)jjte000;}
      }
      {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
    throw new Error("Missing return statement in function");
}

  final public void boolTermPrime(ExpType inheritedType) throws ParseException {/*@bgen(jjtree) boolTermPrime */
 ASTboolTermPrime jjtn000 = new ASTboolTermPrime(JJTBOOLTERMPRIME);
 boolean jjtc000 = true;
 jjtree.openNodeScope(jjtn000);ExpType type;
    try {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case AND:{
        jj_consume_token(AND);
        type = boolFactor();
        boolTermPrime(type);
        break;
        }
      default:
        jj_la1[23] = jj_gen;
jjtree.closeNodeScope(jjtn000, true);
      jjtc000 = false;

      }
    } catch (Throwable jjte000) {
if (jjtc000) {
        jjtree.clearNodeScope(jjtn000);
        jjtc000 = false;
      } else {
        jjtree.popNode();
      }
      if (jjte000 instanceof RuntimeException) {
        {if (true) throw (RuntimeException)jjte000;}
      }
      if (jjte000 instanceof ParseException) {
        {if (true) throw (ParseException)jjte000;}
      }
      {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
}

  final public ExpType boolFactor() throws ParseException {/*@bgen(jjtree) boolFactor */
 ASTboolFactor jjtn000 = new ASTboolFactor(JJTBOOLFACTOR);
 boolean jjtc000 = true;
 jjtree.openNodeScope(jjtn000);ExpType type;
    try {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case NOT:{
        jj_consume_token(NOT);
        type = boolVal();
        break;
        }
      case NUMBER:
      case TRUE:
      case FALSE:
      case IDENTIFIER:
      case LPAREN:
      case MINUS:{
        type = boolVal();
jjtree.closeNodeScope(jjtn000, true);
      jjtc000 = false;
{if ("" != null) return type;}
        break;
        }
      default:
        jj_la1[24] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    } catch (Throwable jjte000) {
if (jjtc000) {
        jjtree.clearNodeScope(jjtn000);
        jjtc000 = false;
      } else {
        jjtree.popNode();
      }
      if (jjte000 instanceof RuntimeException) {
        {if (true) throw (RuntimeException)jjte000;}
      }
      if (jjte000 instanceof ParseException) {
        {if (true) throw (ParseException)jjte000;}
      }
      {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
    throw new Error("Missing return statement in function");
}

  final public ExpType boolVal() throws ParseException {/*@bgen(jjtree) boolVal */
 ASTboolVal jjtn000 = new ASTboolVal(JJTBOOLVAL);
 boolean jjtc000 = true;
 jjtree.openNodeScope(jjtn000);ExpType type;
    try {
      if (jj_2_4(3)) {
        type = comp();
jjtree.closeNodeScope(jjtn000, true);
                               jjtc000 = false;
{if ("" != null) return type;}
      } else {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case LPAREN:{
          jj_consume_token(LPAREN);
          type = boolExp();
          jj_consume_token(RPAREN);
jjtree.closeNodeScope(jjtn000, true);
                                       jjtc000 = false;
{if ("" != null) return type;}
          break;
          }
        default:
          jj_la1[25] = jj_gen;
          if (jj_2_5(2)) {
            functionCall();
jjtree.closeNodeScope(jjtn000, true);
                                  jjtc000 = false;
{if ("" != null) return ExpType.FunctionCall;}
          } else {
            switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
            case IDENTIFIER:{
              variableIdentifier();
jjtree.closeNodeScope(jjtn000, true);
                           jjtc000 = false;
{if ("" != null) return ExpType.Variable;}
              break;
              }
            case TRUE:{
              jj_consume_token(TRUE);
jjtree.closeNodeScope(jjtn000, true);
             jjtc000 = false;
{if ("" != null) return ExpType.Boolean;}
              break;
              }
            case FALSE:{
              jj_consume_token(FALSE);
jjtree.closeNodeScope(jjtn000, true);
              jjtc000 = false;
{if ("" != null) return ExpType.Boolean;}
              break;
              }
            default:
              jj_la1[26] = jj_gen;
              jj_consume_token(-1);
              throw new ParseException();
            }
          }
        }
      }
    } catch (Throwable jjte000) {
if (jjtc000) {
        jjtree.clearNodeScope(jjtn000);
        jjtc000 = false;
      } else {
        jjtree.popNode();
      }
      if (jjte000 instanceof RuntimeException) {
        {if (true) throw (RuntimeException)jjte000;}
      }
      if (jjte000 instanceof ParseException) {
        {if (true) throw (ParseException)jjte000;}
      }
      {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
    throw new Error("Missing return statement in function");
}

  final public ExpType comp() throws ParseException {/*@bgen(jjtree) comp */
  ASTcomp jjtn000 = new ASTcomp(JJTCOMP);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      arthExp();
      compOp();
      arthExp();
jjtree.closeNodeScope(jjtn000, true);
      jjtc000 = false;
{if ("" != null) return ExpType.Boolean;}
    } catch (Throwable jjte000) {
if (jjtc000) {
        jjtree.clearNodeScope(jjtn000);
        jjtc000 = false;
      } else {
        jjtree.popNode();
      }
      if (jjte000 instanceof RuntimeException) {
        {if (true) throw (RuntimeException)jjte000;}
      }
      if (jjte000 instanceof ParseException) {
        {if (true) throw (ParseException)jjte000;}
      }
      {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
    throw new Error("Missing return statement in function");
}

  final public void compOp() throws ParseException {/*@bgen(jjtree) compOp */
  ASTcompOp jjtn000 = new ASTcompOp(JJTCOMPOP);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case LESS:{
        jj_consume_token(LESS);
        break;
        }
      case GREATER:{
        jj_consume_token(GREATER);
        break;
        }
      case LESSEQUAL:{
        jj_consume_token(LESSEQUAL);
        break;
        }
      case GREATEREQUAL:{
        jj_consume_token(GREATEREQUAL);
        break;
        }
      case EQUAL:{
        jj_consume_token(EQUAL);
        break;
        }
      case NOTEQUAL:{
        jj_consume_token(NOTEQUAL);
        break;
        }
      default:
        jj_la1[27] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
}

// Function Calls
  final public ExpType functionCall() throws ParseException {/*@bgen(jjtree) functionCall */
 ASTfunctionCall jjtn000 = new ASTfunctionCall(JJTFUNCTIONCALL);
 boolean jjtc000 = true;
 jjtree.openNodeScope(jjtn000);Token id;
    try {
      id = identifier();
      actualParameterList();
jjtree.closeNodeScope(jjtn000, true);
     jjtc000 = false;
jjtn000.functionName = id.image;
    {if ("" != null) return ExpType.FunctionCall;}
    } catch (Throwable jjte000) {
if (jjtc000) {
        jjtree.clearNodeScope(jjtn000);
        jjtc000 = false;
      } else {
        jjtree.popNode();
      }
      if (jjte000 instanceof RuntimeException) {
        {if (true) throw (RuntimeException)jjte000;}
      }
      if (jjte000 instanceof ParseException) {
        {if (true) throw (ParseException)jjte000;}
      }
      {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
    throw new Error("Missing return statement in function");
}

  final public void actualParameterList() throws ParseException {/*@bgen(jjtree) actualParameterList */
  ASTactualParameterList jjtn000 = new ASTactualParameterList(JJTACTUALPARAMETERLIST);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(LPAREN);
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case NUMBER:
      case TRUE:
      case FALSE:
      case IDENTIFIER:
      case STRING:{
        actualParameter();
        label_7:
        while (true) {
          switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
          case COMMA:{
            ;
            break;
            }
          default:
            jj_la1[28] = jj_gen;
            break label_7;
          }
          jj_consume_token(COMMA);
          actualParameter();
        }
        break;
        }
      default:
        jj_la1[29] = jj_gen;
        ;
      }
      jj_consume_token(RPAREN);
    } catch (Throwable jjte000) {
if (jjtc000) {
        jjtree.clearNodeScope(jjtn000);
        jjtc000 = false;
      } else {
        jjtree.popNode();
      }
      if (jjte000 instanceof RuntimeException) {
        {if (true) throw (RuntimeException)jjte000;}
      }
      if (jjte000 instanceof ParseException) {
        {if (true) throw (ParseException)jjte000;}
      }
      {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
}

  final public void actualParameter() throws ParseException {/*@bgen(jjtree) actualParameter */
                          ASTactualParameter jjtn000 = new ASTactualParameter(JJTACTUALPARAMETER);
                          boolean jjtc000 = true;
                          jjtree.openNodeScope(jjtn000);String type;Boolean isIdentifier = false;
    try {
      if (jj_2_6(2)) {
        type = variableIdentifier();
jjtree.closeNodeScope(jjtn000, true);
                                             jjtc000 = false;
jjtn000.isIdentifier= true;jjtn000.type =type;
      } else {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case STRING:{
          jj_consume_token(STRING);
jjtree.closeNodeScope(jjtn000, true);
               jjtc000 = false;
type = "string"; jjtn000.type =type; jjtn000.isIdentifier=false;
          break;
          }
        case TRUE:{
          jj_consume_token(TRUE);
jjtree.closeNodeScope(jjtn000, true);
             jjtc000 = false;
type = "bool"; jjtn000.type =type;jjtn000.isIdentifier=false;
          break;
          }
        case FALSE:{
          jj_consume_token(FALSE);
jjtree.closeNodeScope(jjtn000, true);
              jjtc000 = false;
type = "bool"; jjtn000.type =type;jjtn000.isIdentifier=false;
          break;
          }
        case NUMBER:{
          type = number();
jjtree.closeNodeScope(jjtn000, true);
                    jjtc000 = false;
jjtn000.type =type;jjtn000.isIdentifier=false;
          break;
          }
        default:
          jj_la1[30] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
      }
    } catch (Throwable jjte000) {
if (jjtc000) {
        jjtree.clearNodeScope(jjtn000);
        jjtc000 = false;
      } else {
        jjtree.popNode();
      }
      if (jjte000 instanceof RuntimeException) {
        {if (true) throw (RuntimeException)jjte000;}
      }
      if (jjte000 instanceof ParseException) {
        {if (true) throw (ParseException)jjte000;}
      }
      {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
}

  private boolean jj_2_1(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_1()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(0, xla); }
  }

  private boolean jj_2_2(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_2()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(1, xla); }
  }

  private boolean jj_2_3(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_3()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(2, xla); }
  }

  private boolean jj_2_4(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_4()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(3, xla); }
  }

  private boolean jj_2_5(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_5()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(4, xla); }
  }

  private boolean jj_2_6(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_6()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(5, xla); }
  }

  private boolean jj_3R_assignmentStatement_277_5_13()
 {
    if (jj_3R_expression_342_5_19()) return true;
    return false;
  }

  private boolean jj_3R_assignmentStatement_275_4_8()
 {
    if (jj_3R_variableIdentifier_336_5_12()) return true;
    if (jj_scan_token(ASSIGN)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_assignmentStatement_277_5_13()) {
    jj_scanpos = xsp;
    if (jj_scan_token(47)) return true;
    }
    return false;
  }

  private boolean jj_3R_arthExpPrime_369_5_24()
 {
    return false;
  }

  private boolean jj_3R_boolVal_462_5_48()
 {
    if (jj_scan_token(LPAREN)) return true;
    return false;
  }

  private boolean jj_3R_arthExpPrime_367_5_23()
 {
    if (jj_scan_token(MINUS)) return true;
    if (jj_3R_arthTerm_375_5_14()) return true;
    return false;
  }

  private boolean jj_3_1()
 {
    if (jj_3R_assignmentStatement_275_4_8()) return true;
    return false;
  }

  private boolean jj_3R_arthExpPrime_365_5_15()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_arthExpPrime_365_5_22()) {
    jj_scanpos = xsp;
    if (jj_3R_arthExpPrime_367_5_23()) {
    jj_scanpos = xsp;
    if (jj_3R_arthExpPrime_369_5_24()) return true;
    }
    }
    return false;
  }

  private boolean jj_3R_arthExpPrime_365_5_22()
 {
    if (jj_scan_token(PLUS)) return true;
    if (jj_3R_arthTerm_375_5_14()) return true;
    return false;
  }

  private boolean jj_3_4()
 {
    if (jj_3R_comp_483_5_11()) return true;
    return false;
  }

  private boolean jj_3R_boolVal_456_5_47()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_4()) {
    jj_scanpos = xsp;
    if (jj_3R_boolVal_462_5_48()) {
    jj_scanpos = xsp;
    if (jj_3_5()) {
    jj_scanpos = xsp;
    if (jj_3R_boolVal_472_5_49()) {
    jj_scanpos = xsp;
    if (jj_3R_boolVal_474_5_50()) {
    jj_scanpos = xsp;
    if (jj_3R_boolVal_476_5_51()) return true;
    }
    }
    }
    }
    }
    return false;
  }

  private boolean jj_3R_arthExp_358_5_9()
 {
    if (jj_3R_arthTerm_375_5_14()) return true;
    if (jj_3R_arthExpPrime_365_5_15()) return true;
    return false;
  }

  private boolean jj_3R_boolFactor_449_5_46()
 {
    if (jj_3R_boolVal_456_5_47()) return true;
    return false;
  }

  private boolean jj_3R_boolFactor_447_5_45()
 {
    if (jj_scan_token(NOT)) return true;
    return false;
  }

  private boolean jj_3R_boolFactor_447_5_44()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_boolFactor_447_5_45()) {
    jj_scanpos = xsp;
    if (jj_3R_boolFactor_449_5_46()) return true;
    }
    return false;
  }

  private boolean jj_3R_expression_351_5_26()
 {
    if (jj_3R_boolExp_419_5_33()) return true;
    return false;
  }

  private boolean jj_3R_actualParameter_540_5_38()
 {
    if (jj_3R_number_411_5_43()) return true;
    return false;
  }

  private boolean jj_3R_actualParameter_539_5_37()
 {
    if (jj_scan_token(FALSE)) return true;
    return false;
  }

  private boolean jj_3_2()
 {
    if (jj_3R_arthExp_358_5_9()) return true;
    return false;
  }

  private boolean jj_3R_actualParameter_538_5_36()
 {
    if (jj_scan_token(TRUE)) return true;
    return false;
  }

  private boolean jj_3R_actualParameter_537_5_35()
 {
    if (jj_scan_token(STRING)) return true;
    return false;
  }

  private boolean jj_3_6()
 {
    if (jj_3R_variableIdentifier_336_5_12()) return true;
    return false;
  }

  private boolean jj_3R_expression_342_5_19()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_2()) {
    jj_scanpos = xsp;
    if (jj_3R_expression_351_5_26()) return true;
    }
    return false;
  }

  private boolean jj_3R_boolTerm_433_5_39()
 {
    if (jj_3R_boolFactor_447_5_44()) return true;
    return false;
  }

  private boolean jj_3R_variableIdentifier_336_5_12()
 {
    if (jj_3R_identifier_330_5_16()) return true;
    return false;
  }

  private boolean jj_3R_actualParameterList_516_15_25()
 {
    if (jj_3R_actualParameter_521_5_32()) return true;
    return false;
  }

  private boolean jj_3R_actualParameter_521_5_32()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_6()) {
    jj_scanpos = xsp;
    if (jj_3R_actualParameter_537_5_35()) {
    jj_scanpos = xsp;
    if (jj_3R_actualParameter_538_5_36()) {
    jj_scanpos = xsp;
    if (jj_3R_actualParameter_539_5_37()) {
    jj_scanpos = xsp;
    if (jj_3R_actualParameter_540_5_38()) return true;
    }
    }
    }
    }
    return false;
  }

  private boolean jj_3R_identifier_330_5_16()
 {
    if (jj_scan_token(IDENTIFIER)) return true;
    return false;
  }

  private boolean jj_3R_actualParameterList_516_5_17()
 {
    if (jj_scan_token(LPAREN)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_actualParameterList_516_15_25()) jj_scanpos = xsp;
    if (jj_scan_token(RPAREN)) return true;
    return false;
  }

  private boolean jj_3R_boolExp_419_5_33()
 {
    if (jj_3R_boolTerm_433_5_39()) return true;
    return false;
  }

  private boolean jj_3R_functionCall_507_5_10()
 {
    if (jj_3R_identifier_330_5_16()) return true;
    if (jj_3R_actualParameterList_516_5_17()) return true;
    return false;
  }

  private boolean jj_3R_number_411_5_43()
 {
    if (jj_scan_token(NUMBER)) return true;
    return false;
  }

  private boolean jj_3R_numValue_404_5_42()
 {
    if (jj_3R_number_411_5_43()) return true;
    return false;
  }

  private boolean jj_3R_numValue_402_5_41()
 {
    if (jj_scan_token(LPAREN)) return true;
    if (jj_3R_arthExp_358_5_9()) return true;
    if (jj_scan_token(RPAREN)) return true;
    return false;
  }

  private boolean jj_3R_numValue_400_5_40()
 {
    if (jj_3R_variableIdentifier_336_5_12()) return true;
    return false;
  }

  private boolean jj_3_3()
 {
    if (jj_3R_functionCall_507_5_10()) return true;
    return false;
  }

  private boolean jj_3R_numValue_398_5_34()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_3()) {
    jj_scanpos = xsp;
    if (jj_3R_numValue_400_5_40()) {
    jj_scanpos = xsp;
    if (jj_3R_numValue_402_5_41()) {
    jj_scanpos = xsp;
    if (jj_3R_numValue_404_5_42()) return true;
    }
    }
    }
    return false;
  }

  private boolean jj_3R_compOp_490_5_18()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(41)) {
    jj_scanpos = xsp;
    if (jj_scan_token(42)) {
    jj_scanpos = xsp;
    if (jj_scan_token(43)) {
    jj_scanpos = xsp;
    if (jj_scan_token(44)) {
    jj_scanpos = xsp;
    if (jj_scan_token(45)) {
    jj_scanpos = xsp;
    if (jj_scan_token(46)) return true;
    }
    }
    }
    }
    }
    return false;
  }

  private boolean jj_3R_arthFactor_393_5_28()
 {
    if (jj_3R_numValue_398_5_34()) return true;
    return false;
  }

  private boolean jj_3R_arthFactor_391_5_20()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_arthFactor_391_5_27()) {
    jj_scanpos = xsp;
    if (jj_3R_arthFactor_393_5_28()) return true;
    }
    return false;
  }

  private boolean jj_3R_arthFactor_391_5_27()
 {
    if (jj_scan_token(MINUS)) return true;
    if (jj_3R_numValue_398_5_34()) return true;
    return false;
  }

  private boolean jj_3R_comp_483_5_11()
 {
    if (jj_3R_arthExp_358_5_9()) return true;
    if (jj_3R_compOp_490_5_18()) return true;
    if (jj_3R_arthExp_358_5_9()) return true;
    return false;
  }

  private boolean jj_3R_arthTermPrime_384_5_31()
 {
    return false;
  }

  private boolean jj_3R_arthTermPrime_382_5_30()
 {
    if (jj_scan_token(DIVIDE)) return true;
    if (jj_3R_arthFactor_391_5_20()) return true;
    return false;
  }

  private boolean jj_3R_boolVal_476_5_51()
 {
    if (jj_scan_token(FALSE)) return true;
    return false;
  }

  private boolean jj_3R_arthTermPrime_380_5_21()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_arthTermPrime_380_5_29()) {
    jj_scanpos = xsp;
    if (jj_3R_arthTermPrime_382_5_30()) {
    jj_scanpos = xsp;
    if (jj_3R_arthTermPrime_384_5_31()) return true;
    }
    }
    return false;
  }

  private boolean jj_3R_arthTermPrime_380_5_29()
 {
    if (jj_scan_token(MULTIPLY)) return true;
    if (jj_3R_arthFactor_391_5_20()) return true;
    return false;
  }

  private boolean jj_3R_boolVal_474_5_50()
 {
    if (jj_scan_token(TRUE)) return true;
    return false;
  }

  private boolean jj_3R_boolVal_472_5_49()
 {
    if (jj_3R_variableIdentifier_336_5_12()) return true;
    return false;
  }

  private boolean jj_3R_arthTerm_375_5_14()
 {
    if (jj_3R_arthFactor_391_5_20()) return true;
    if (jj_3R_arthTermPrime_380_5_21()) return true;
    return false;
  }

  private boolean jj_3_5()
 {
    if (jj_3R_functionCall_507_5_10()) return true;
    return false;
  }

  /** Generated Token Manager. */
  public MyGrammarTokenManager token_source;
  SimpleCharStream jj_input_stream;
  /** Current token. */
  public Token token;
  /** Next token. */
  public Token jj_nt;
  private int jj_ntk;
  private Token jj_scanpos, jj_lastpos;
  private int jj_la;
  private int jj_gen;
  final private int[] jj_la1 = new int[31];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static {
	   jj_la1_init_0();
	   jj_la1_init_1();
	}
	private static void jj_la1_init_0() {
	   jj_la1_0 = new int[] {0x8000,0x10000,0x0,0x40000000,0x0,0x0,0x20000,0x40000000,0x40500000,0x40500000,0x40500000,0x40000000,0x4e000400,0x500000,0x1000000,0x0,0x3800,0x4e000400,0x0,0x0,0x40000400,0x40000400,0x10000000,0x20000000,0x4e000400,0x0,0x46000000,0x0,0x0,0x46000400,0x6000400,};
	}
	private static void jj_la1_init_1() {
	   jj_la1_1 = new int[] {0x0,0x0,0x1,0x0,0x4,0x1,0x0,0x0,0x0,0x0,0x0,0x0,0x8041,0x0,0x0,0x4,0x0,0x41,0x60,0x180,0x41,0x1,0x0,0x0,0x41,0x1,0x0,0x7e00,0x4,0x8000,0x8000,};
	}
  final private JJCalls[] jj_2_rtns = new JJCalls[6];
  private boolean jj_rescan = false;
  private int jj_gc = 0;

  /** Constructor with InputStream. */
  public MyGrammar(java.io.InputStream stream) {
	  this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public MyGrammar(java.io.InputStream stream, String encoding) {
	 try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
	 token_source = new MyGrammarTokenManager(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 31; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream) {
	  ReInit(stream, null);
  }
  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream, String encoding) {
	 try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
	 token_source.ReInit(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jjtree.reset();
	 jj_gen = 0;
	 for (int i = 0; i < 31; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor. */
  public MyGrammar(java.io.Reader stream) {
	 jj_input_stream = new SimpleCharStream(stream, 1, 1);
	 token_source = new MyGrammarTokenManager(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 31; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(java.io.Reader stream) {
	if (jj_input_stream == null) {
	   jj_input_stream = new SimpleCharStream(stream, 1, 1);
	} else {
	   jj_input_stream.ReInit(stream, 1, 1);
	}
	if (token_source == null) {
 token_source = new MyGrammarTokenManager(jj_input_stream);
	}

	 token_source.ReInit(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jjtree.reset();
	 jj_gen = 0;
	 for (int i = 0; i < 31; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor with generated Token Manager. */
  public MyGrammar(MyGrammarTokenManager tm) {
	 token_source = tm;
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 31; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(MyGrammarTokenManager tm) {
	 token_source = tm;
	 token = new Token();
	 jj_ntk = -1;
	 jjtree.reset();
	 jj_gen = 0;
	 for (int i = 0; i < 31; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  private Token jj_consume_token(int kind) throws ParseException {
	 Token oldToken;
	 if ((oldToken = token).next != null) token = token.next;
	 else token = token.next = token_source.getNextToken();
	 jj_ntk = -1;
	 if (token.kind == kind) {
	   jj_gen++;
	   if (++jj_gc > 100) {
		 jj_gc = 0;
		 for (int i = 0; i < jj_2_rtns.length; i++) {
		   JJCalls c = jj_2_rtns[i];
		   while (c != null) {
			 if (c.gen < jj_gen) c.first = null;
			 c = c.next;
		   }
		 }
	   }
	   return token;
	 }
	 token = oldToken;
	 jj_kind = kind;
	 throw generateParseException();
  }

  @SuppressWarnings("serial")
  static private final class LookaheadSuccess extends java.lang.Error {
    @Override
    public Throwable fillInStackTrace() {
      return this;
    }
  }
  static private final LookaheadSuccess jj_ls = new LookaheadSuccess();
  private boolean jj_scan_token(int kind) {
	 if (jj_scanpos == jj_lastpos) {
	   jj_la--;
	   if (jj_scanpos.next == null) {
		 jj_lastpos = jj_scanpos = jj_scanpos.next = token_source.getNextToken();
	   } else {
		 jj_lastpos = jj_scanpos = jj_scanpos.next;
	   }
	 } else {
	   jj_scanpos = jj_scanpos.next;
	 }
	 if (jj_rescan) {
	   int i = 0; Token tok = token;
	   while (tok != null && tok != jj_scanpos) { i++; tok = tok.next; }
	   if (tok != null) jj_add_error_token(kind, i);
	 }
	 if (jj_scanpos.kind != kind) return true;
	 if (jj_la == 0 && jj_scanpos == jj_lastpos) throw jj_ls;
	 return false;
  }


/** Get the next Token. */
  final public Token getNextToken() {
	 if (token.next != null) token = token.next;
	 else token = token.next = token_source.getNextToken();
	 jj_ntk = -1;
	 jj_gen++;
	 return token;
  }

/** Get the specific Token. */
  final public Token getToken(int index) {
	 Token t = token;
	 for (int i = 0; i < index; i++) {
	   if (t.next != null) t = t.next;
	   else t = t.next = token_source.getNextToken();
	 }
	 return t;
  }

  private int jj_ntk_f() {
	 if ((jj_nt=token.next) == null)
	   return (jj_ntk = (token.next=token_source.getNextToken()).kind);
	 else
	   return (jj_ntk = jj_nt.kind);
  }

  private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  private int[] jj_expentry;
  private int jj_kind = -1;
  private int[] jj_lasttokens = new int[100];
  private int jj_endpos;

  private void jj_add_error_token(int kind, int pos) {
	 if (pos >= 100) {
		return;
	 }

	 if (pos == jj_endpos + 1) {
	   jj_lasttokens[jj_endpos++] = kind;
	 } else if (jj_endpos != 0) {
	   jj_expentry = new int[jj_endpos];

	   for (int i = 0; i < jj_endpos; i++) {
		 jj_expentry[i] = jj_lasttokens[i];
	   }

	   for (int[] oldentry : jj_expentries) {
		 if (oldentry.length == jj_expentry.length) {
		   boolean isMatched = true;

		   for (int i = 0; i < jj_expentry.length; i++) {
			 if (oldentry[i] != jj_expentry[i]) {
			   isMatched = false;
			   break;
			 }

		   }
		   if (isMatched) {
			 jj_expentries.add(jj_expentry);
			 break;
		   }
		 }
	   }

	   if (pos != 0) {
		 jj_lasttokens[(jj_endpos = pos) - 1] = kind;
	   }
	 }
  }

  /** Generate ParseException. */
  public ParseException generateParseException() {
	 jj_expentries.clear();
	 boolean[] la1tokens = new boolean[48];
	 if (jj_kind >= 0) {
	   la1tokens[jj_kind] = true;
	   jj_kind = -1;
	 }
	 for (int i = 0; i < 31; i++) {
	   if (jj_la1[i] == jj_gen) {
		 for (int j = 0; j < 32; j++) {
		   if ((jj_la1_0[i] & (1<<j)) != 0) {
			 la1tokens[j] = true;
		   }
		   if ((jj_la1_1[i] & (1<<j)) != 0) {
			 la1tokens[32+j] = true;
		   }
		 }
	   }
	 }
	 for (int i = 0; i < 48; i++) {
	   if (la1tokens[i]) {
		 jj_expentry = new int[1];
		 jj_expentry[0] = i;
		 jj_expentries.add(jj_expentry);
	   }
	 }
	 jj_endpos = 0;
	 jj_rescan_token();
	 jj_add_error_token(0, 0);
	 int[][] exptokseq = new int[jj_expentries.size()][];
	 for (int i = 0; i < jj_expentries.size(); i++) {
	   exptokseq[i] = jj_expentries.get(i);
	 }
	 return new ParseException(token, exptokseq, tokenImage);
  }

  private boolean trace_enabled;

/** Trace enabled. */
  final public boolean trace_enabled() {
	 return trace_enabled;
  }

  /** Enable tracing. */
  final public void enable_tracing() {
  }

  /** Disable tracing. */
  final public void disable_tracing() {
  }

  private void jj_rescan_token() {
	 jj_rescan = true;
	 for (int i = 0; i < 6; i++) {
	   try {
		 JJCalls p = jj_2_rtns[i];

		 do {
		   if (p.gen > jj_gen) {
			 jj_la = p.arg; jj_lastpos = jj_scanpos = p.first;
			 switch (i) {
			   case 0: jj_3_1(); break;
			   case 1: jj_3_2(); break;
			   case 2: jj_3_3(); break;
			   case 3: jj_3_4(); break;
			   case 4: jj_3_5(); break;
			   case 5: jj_3_6(); break;
			 }
		   }
		   p = p.next;
		 } while (p != null);

		 } catch(LookaheadSuccess ls) { }
	 }
	 jj_rescan = false;
  }

  private void jj_save(int index, int xla) {
	 JJCalls p = jj_2_rtns[index];
	 while (p.gen > jj_gen) {
	   if (p.next == null) { p = p.next = new JJCalls(); break; }
	   p = p.next;
	 }

	 p.gen = jj_gen + xla - jj_la; 
	 p.first = token;
	 p.arg = xla;
  }

  static final class JJCalls {
	 int gen;
	 Token first;
	 int arg;
	 JJCalls next;
  }

}
