/* Generated By:JavaCC: Do not edit this line. MyGrammarTreeConstants.java Version 7.0.13 */
package main.jjtree;

public interface MyGrammarTreeConstants
{
  public int JJTSTART = 0;
  public int JJTPROGRAMHEADING = 1;
  public int JJTFUNCTIONDECLARATION = 2;
  public int JJTFUNCTIONHEADING = 3;
  public int JJTFUNCTIONBODY = 4;
  public int JJTFORMALPARAMETERLIST = 5;
  public int JJTFORMALPARAMETERSECTION = 6;
  public int JJTPROCEDUREDECLARATION = 7;
  public int JJTPROCEDUREHEADING = 8;
  public int JJTPROCEDUREBODY = 9;
  public int JJTBLOCK = 10;
  public int JJTVARIABLEDECLARATIONPART = 11;
  public int JJTVARIABLEDECLARATION = 12;
  public int JJTSTATEMENTPART = 13;
  public int JJTSTATEMENTSEQUENCE = 14;
  public int JJTSTATEMENT = 15;
  public int JJTSIMPLESTATEMENT = 16;
  public int JJTASSIGNMENTSTATEMENT = 17;
  public int JJTPROCEDURECALL = 18;
  public int JJTSTRUCTUREDSTATEMENT = 19;
  public int JJTWHILESTATEMENT = 20;
  public int JJTIFSTATEMENT = 21;
  public int JJTIDENTIFIERLIST = 22;
  public int JJTTYPEIDENTIFIER = 23;
  public int JJTIDENTIFIER = 24;
  public int JJTVARIABLEIDENTIFIER = 25;
  public int JJTEXPRESSION = 26;
  public int JJTARTHEXP = 27;
  public int JJTARTHEXPPRIME = 28;
  public int JJTARTHTERM = 29;
  public int JJTARTHTERMPRIME = 30;
  public int JJTARTHFACTOR = 31;
  public int JJTNUMVALUE = 32;
  public int JJTNUMBER = 33;
  public int JJTBOOLEXP = 34;
  public int JJTBOOLEXPPRIME = 35;
  public int JJTBOOLTERM = 36;
  public int JJTBOOLTERMPRIME = 37;
  public int JJTBOOLFACTOR = 38;
  public int JJTBOOLVAL = 39;
  public int JJTCOMP = 40;
  public int JJTCOMPOP = 41;
  public int JJTFUNCTIONCALL = 42;
  public int JJTACTUALPARAMETERLIST = 43;
  public int JJTACTUALPARAMETER = 44;


  public String[] jjtNodeName = {
    "Start",
    "programHeading",
    "functionDeclaration",
    "functionHeading",
    "functionBody",
    "formalParameterList",
    "formalParameterSection",
    "procedureDeclaration",
    "procedureHeading",
    "procedureBody",
    "block",
    "variableDeclarationPart",
    "variableDeclaration",
    "statementPart",
    "statementSequence",
    "statement",
    "simpleStatement",
    "assignmentStatement",
    "procedureCall",
    "structuredStatement",
    "whileStatement",
    "ifStatement",
    "identifierList",
    "typeIdentifier",
    "identifier",
    "variableIdentifier",
    "expression",
    "arthExp",
    "arthExpPrime",
    "arthTerm",
    "arthTermPrime",
    "arthFactor",
    "numValue",
    "number",
    "boolExp",
    "boolExpPrime",
    "boolTerm",
    "boolTermPrime",
    "boolFactor",
    "boolVal",
    "comp",
    "compOp",
    "functionCall",
    "actualParameterList",
    "actualParameter",
  };
}
/* JavaCC - OriginalChecksum=7eede7bd7197f5f74abc81a20508205c (do not edit this line) */
