/* Generated By:JavaCC: Do not edit this line. MyGrammarDefaultVisitor.java Version 7.0.13 */
package main.jjtree;

public class MyGrammarDefaultVisitor implements MyGrammarVisitor{
  public Object defaultVisit(SimpleNode node, Object data){
    node.childrenAccept(this, data);
    return data;
  }
  public Object visit(SimpleNode node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTStart node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTprogramHeading node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTfunctionDeclaration node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTfunctionHeading node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTfunctionBody node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTformalParameterList node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTformalParameterSection node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTprocedureDeclaration node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTprocedureHeading node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTprocedureBody node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTblock node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTvariableDeclarationPart node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTvariableDeclaration node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTstatementPart node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTstatementSequence node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTstatement node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTsimpleStatement node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTassignmentStatement node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTprocedureCall node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTstructuredStatement node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTwhileStatement node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTifStatement node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTidentifierList node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTtypeIdentifier node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTidentifier node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTvariableIdentifier node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTExpression node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTAndExpression node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTEqualityExpression node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTRelationalExpression node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTAdditiveExpression node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTMultiplicativeExpression node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTUnaryExpression node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTN node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTLiteralExpression node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTfunctionCall node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTactualParameterList node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTactualParameter node, Object data){
    return defaultVisit(node, data);
  }
}
/* JavaCC - OriginalChecksum=3147a86a2770ffeea2a568728eaffcde (do not edit this line) */
