/* Generated By:JJTree&JavaCC: Do not edit this line. MyGrammarConstants.java */
package main.jjtree;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface MyGrammarConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int MINLETTER = 7;
  /** RegularExpression Id. */
  int CAPLETTER = 8;
  /** RegularExpression Id. */
  int DIGIT = 9;
  /** RegularExpression Id. */
  int NUMBER = 10;
  /** RegularExpression Id. */
  int NUMBER_KEYWORD = 11;
  /** RegularExpression Id. */
  int STRING_KEYWORD = 12;
  /** RegularExpression Id. */
  int BOOL_KEYWORD = 13;
  /** RegularExpression Id. */
  int PROGRAM = 14;
  /** RegularExpression Id. */
  int FUNCTION = 15;
  /** RegularExpression Id. */
  int PROCEDURE = 16;
  /** RegularExpression Id. */
  int VAR = 17;
  /** RegularExpression Id. */
  int BEGIN = 18;
  /** RegularExpression Id. */
  int END = 19;
  /** RegularExpression Id. */
  int WHILE = 20;
  /** RegularExpression Id. */
  int DO = 21;
  /** RegularExpression Id. */
  int IF = 22;
  /** RegularExpression Id. */
  int THEN = 23;
  /** RegularExpression Id. */
  int ELSE = 24;
  /** RegularExpression Id. */
  int TRUE = 25;
  /** RegularExpression Id. */
  int FALSE = 26;
  /** RegularExpression Id. */
  int NOT = 27;
  /** RegularExpression Id. */
  int OR = 28;
  /** RegularExpression Id. */
  int AND = 29;
  /** RegularExpression Id. */
  int IDENTIFIER = 30;
  /** RegularExpression Id. */
  int ASSIGN = 31;
  /** RegularExpression Id. */
  int LPAREN = 32;
  /** RegularExpression Id. */
  int RPAREN = 33;
  /** RegularExpression Id. */
  int COMMA = 34;
  /** RegularExpression Id. */
  int COLON = 35;
  /** RegularExpression Id. */
  int SEMICOLON = 36;
  /** RegularExpression Id. */
  int PLUS = 37;
  /** RegularExpression Id. */
  int MINUS = 38;
  /** RegularExpression Id. */
  int MULTIPLY = 39;
  /** RegularExpression Id. */
  int DIVIDE = 40;
  /** RegularExpression Id. */
  int LESS = 41;
  /** RegularExpression Id. */
  int GREATER = 42;
  /** RegularExpression Id. */
  int LESSEQUAL = 43;
  /** RegularExpression Id. */
  int GREATEREQUAL = 44;
  /** RegularExpression Id. */
  int EQUAL = 45;
  /** RegularExpression Id. */
  int NOTEQUAL = 46;
  /** RegularExpression Id. */
  int STRING = 47;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\\' \\\'\"",
    "\"\\\'\\\'\"",
    "<MINLETTER>",
    "<CAPLETTER>",
    "<DIGIT>",
    "<NUMBER>",
    "\"number\"",
    "\"string\"",
    "\"bool\"",
    "\"program\"",
    "\"function\"",
    "\"procedure\"",
    "\"var\"",
    "\"begin\"",
    "\"end\"",
    "\"while\"",
    "\"do\"",
    "\"if\"",
    "\"then\"",
    "\"else\"",
    "\"true\"",
    "\"false\"",
    "\"NOT\"",
    "\"OR\"",
    "\"AND\"",
    "<IDENTIFIER>",
    "\":=\"",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\":\"",
    "\";\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"<\"",
    "\">\"",
    "\"<=\"",
    "\">=\"",
    "\"==\"",
    "\"!=\"",
    "<STRING>",
  };

}
