/* Generated By:JavaCC: Do not edit this line. MyGrammarVisitor.java Version 7.0.13 */
package main.jjtree;

public interface MyGrammarVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ASTStart node, Object data);
  public Object visit(ASTprogramHeading node, Object data);
  public Object visit(ASTfunctionDeclaration node, Object data);
  public Object visit(ASTfunctionHeading node, Object data);
  public Object visit(ASTfunctionBody node, Object data);
  public Object visit(ASTformalParameterList node, Object data);
  public Object visit(ASTformalParameterSection node, Object data);
  public Object visit(ASTprocedureDeclaration node, Object data);
  public Object visit(ASTprocedureHeading node, Object data);
  public Object visit(ASTprocedureBody node, Object data);
  public Object visit(ASTblock node, Object data);
  public Object visit(ASTvariableDeclarationPart node, Object data);
  public Object visit(ASTvariableDeclaration node, Object data);
  public Object visit(ASTstatementPart node, Object data);
  public Object visit(ASTstatementSequence node, Object data);
  public Object visit(ASTstatement node, Object data);
  public Object visit(ASTsimpleStatement node, Object data);
  public Object visit(ASTassignmentStatement node, Object data);
  public Object visit(ASTprocedureCall node, Object data);
  public Object visit(ASTstructuredStatement node, Object data);
  public Object visit(ASTwhileStatement node, Object data);
  public Object visit(ASTifStatement node, Object data);
  public Object visit(ASTidentifierList node, Object data);
  public Object visit(ASTtypeIdentifier node, Object data);
  public Object visit(ASTidentifier node, Object data);
  public Object visit(ASTvariableIdentifier node, Object data);
  public Object visit(ASTexpression node, Object data);
  public Object visit(ASTarthExp node, Object data);
  public Object visit(ASTarthExpPrime node, Object data);
  public Object visit(ASTarthTerm node, Object data);
  public Object visit(ASTarthTermPrime node, Object data);
  public Object visit(ASTarthFactor node, Object data);
  public Object visit(ASTnumValue node, Object data);
  public Object visit(ASTnumber node, Object data);
  public Object visit(ASTboolExp node, Object data);
  public Object visit(ASTboolExpPrime node, Object data);
  public Object visit(ASTboolTerm node, Object data);
  public Object visit(ASTboolTermPrime node, Object data);
  public Object visit(ASTboolFactor node, Object data);
  public Object visit(ASTboolVal node, Object data);
  public Object visit(ASTcomp node, Object data);
  public Object visit(ASTcompOp node, Object data);
  public Object visit(ASTfunctionCall node, Object data);
  public Object visit(ASTactualParameterList node, Object data);
  public Object visit(ASTactualParameter node, Object data);
}
/* JavaCC - OriginalChecksum=914d2907340988a0e7a93b5f5c303478 (do not edit this line) */
