/* Generated By:JavaCC: Do not edit this line. MyGrammarTreeConstants.java Version 7.0.13 */
package main.jjtree;

public interface MyGrammarTreeConstants
{
  public int JJTSTART = 0;
  public int JJTPROGRAMHEADING = 1;
  public int JJTFUNCTIONDECLARATION = 2;
  public int JJTFUNCTIONHEADING = 3;
  public int JJTFUNCTIONBODY = 4;
  public int JJTFORMALPARAMETERLIST = 5;
  public int JJTFORMALPARAMETERSECTION = 6;
  public int JJTPROCEDUREDECLARATION = 7;
  public int JJTPROCEDUREHEADING = 8;
  public int JJTPROCEDUREBODY = 9;
  public int JJTBLOCK = 10;
  public int JJTVARIABLEDECLARATIONPART = 11;
  public int JJTVARIABLEDECLARATION = 12;
  public int JJTSTATEMENTPART = 13;
  public int JJTSTATEMENTSEQUENCE = 14;
  public int JJTSTATEMENT = 15;
  public int JJTSIMPLESTATEMENT = 16;
  public int JJTBREAK2 = 17;
  public int JJTPRINTCALL = 18;
  public int JJTASSIGNMENTSTATEMENT = 19;
  public int JJTPROCEDURECALL = 20;
  public int JJTSTRUCTUREDSTATEMENT = 21;
  public int JJTWHILESTATEMENT = 22;
  public int JJTIFSTATEMENT = 23;
  public int JJTIDENTIFIERLIST = 24;
  public int JJTTYPEIDENTIFIER = 25;
  public int JJTIDENTIFIER = 26;
  public int JJTVARIABLEIDENTIFIER = 27;
  public int JJTEXPRESSION = 28;
  public int JJTANDEXPRESSION = 29;
  public int JJTEQUALITYEXPRESSION = 30;
  public int JJTRELATIONALEXPRESSION = 31;
  public int JJTADDITIVEEXPRESSION = 32;
  public int JJTMULTIPLICATIVEEXPRESSION = 33;
  public int JJTUNARYEXPRESSION = 34;
  public int JJTN = 35;
  public int JJTLITERALEXPRESSION = 36;
  public int JJTFUNCTIONCALL = 37;
  public int JJTACTUALPARAMETERLIST = 38;
  public int JJTACTUALPARAMETER = 39;


  public String[] jjtNodeName = {
    "Start",
    "programHeading",
    "functionDeclaration",
    "functionHeading",
    "functionBody",
    "formalParameterList",
    "formalParameterSection",
    "procedureDeclaration",
    "procedureHeading",
    "procedureBody",
    "block",
    "variableDeclarationPart",
    "variableDeclaration",
    "statementPart",
    "statementSequence",
    "statement",
    "simpleStatement",
    "break2",
    "printCall",
    "assignmentStatement",
    "procedureCall",
    "structuredStatement",
    "whileStatement",
    "ifStatement",
    "identifierList",
    "typeIdentifier",
    "identifier",
    "variableIdentifier",
    "Expression",
    "AndExpression",
    "EqualityExpression",
    "RelationalExpression",
    "AdditiveExpression",
    "MultiplicativeExpression",
    "UnaryExpression",
    "N",
    "LiteralExpression",
    "functionCall",
    "actualParameterList",
    "actualParameter",
  };
}
/* JavaCC - OriginalChecksum=6e3df1b02b75d1096b5cc118f16a467f (do not edit this line) */
