/* Generated By:JavaCC: Do not edit this line. MyGrammarVisitor.java Version 7.0.13 */
package main.jjtree;

public interface MyGrammarVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ASTStart node, Object data);
  public Object visit(ASTprogramHeading node, Object data);
  public Object visit(ASTfunctionDeclaration node, Object data);
  public Object visit(ASTfunctionHeading node, Object data);
  public Object visit(ASTfunctionBody node, Object data);
  public Object visit(ASTformalParameterList node, Object data);
  public Object visit(ASTformalParameterSection node, Object data);
  public Object visit(ASTprocedureDeclaration node, Object data);
  public Object visit(ASTprocedureHeading node, Object data);
  public Object visit(ASTprocedureBody node, Object data);
  public Object visit(ASTblock node, Object data);
  public Object visit(ASTvariableDeclarationPart node, Object data);
  public Object visit(ASTvariableDeclaration node, Object data);
  public Object visit(ASTstatementPart node, Object data);
  public Object visit(ASTstatementSequence node, Object data);
  public Object visit(ASTstatement node, Object data);
  public Object visit(ASTsimpleStatement node, Object data);
  public Object visit(ASTbreak2 node, Object data);
  public Object visit(ASTprintCall node, Object data);
  public Object visit(ASTassignmentStatement node, Object data);
  public Object visit(ASTbuiltInCalls node, Object data);
  public Object visit(ASTReadIntCall node, Object data);
  public Object visit(ASTReadStringCall node, Object data);
  public Object visit(ASTprocedureCall node, Object data);
  public Object visit(ASTstructuredStatement node, Object data);
  public Object visit(ASTwhileStatement node, Object data);
  public Object visit(ASTifStatement node, Object data);
  public Object visit(ASTidentifierList node, Object data);
  public Object visit(ASTtypeIdentifier node, Object data);
  public Object visit(ASTidentifier node, Object data);
  public Object visit(ASTvariableIdentifier node, Object data);
  public Object visit(ASTExpression node, Object data);
  public Object visit(ASTAndExpression node, Object data);
  public Object visit(ASTEqualityExpression node, Object data);
  public Object visit(ASTRelationalExpression node, Object data);
  public Object visit(ASTAdditiveExpression node, Object data);
  public Object visit(ASTMultiplicativeExpression node, Object data);
  public Object visit(ASTUnaryExpression node, Object data);
  public Object visit(ASTN node, Object data);
  public Object visit(ASTLiteralExpression node, Object data);
  public Object visit(ASTfunctionCall node, Object data);
  public Object visit(ASTactualParameterList node, Object data);
  public Object visit(ASTactualParameter node, Object data);
}
/* JavaCC - OriginalChecksum=99c975565d3765374f6a0fc00a3acae4 (do not edit this line) */
